# Source: airflow/templates/secrets/fernetkey-secret.yaml
################################
## Airflow Fernet Key Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  labels:
    tier: airflow
type: Opaque
data:
  fernet-key: "Vms1cGRYcHhRa3hqY2pOVVVtcFdabUUxWWpNNVlWTkxabUp0TW5WeVVIbz0="