################################
## Airflow Redis Password Secret
#################################
# If passwordSecretName is not set, we will either use the set password, or use the generated one
apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis-password
  labels:
    tier: airflow
    component: redis
type: Opaque
data:
  password: "WDlHRXBnelRLTA=="