# Source: airflow/templates/secrets/redis-secrets.yaml
##################################
## Airflow Redis Connection Secret
##################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-broker-url
  labels:
    tier: airflow
    component: redis
type: Opaque
data:
  connection: "cmVkaXM6Ly86WDlHRXBnelRLTEBhaXJmbG93LXJlZGlzOjYzNzkvMA=="