# Source: airflow/templates/secrets/metadata-connection-secret.yaml
################################
## Airflow Metadata Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  labels:
    tier: airflow
type: Opaque
data:
  connection: "b3JhY2xlOi8vTURHTk9GRlNIT1JFREVWOk1ER05PRkZTSE9SRURFVjEyI0BkcDFtZWRleDEtc2NhbjE6MjAyNS8/c2VydmljZV9uYW1lPUQzTUdOP2VuY29kaW5nPVVURi04Jm5lbmNvZGluZz1VVEYtOCZ0aHJlYWRlZD1GYWxzZSZldmVudHM9RmFsc2UmbW9kZT1zeXNkYmEmcHVyaXR5PW5ldwo="